name: MonoUI Package

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@resoguy'
      - run: pwd
      - run: npm run bootstrap
      - run: cd ./packages/ui && pwd && npm ci
      - run: pwd
      - run: npm run build:ui
      - run: cd ./packages/ui && pwd && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
